### ISSUE TITLE
子目录的文件看不见，但是搜索可见。

### ISSUE THREAD

**Issue by mzszhznn** [helloqiu/online-explorer#6]
很喜欢online-explorer的设计，不过使用中遇到了个问题
子目录的文件看不见，但是搜索可见。

**Comment by helloqiu** [comment]
是一个路径的bug，原来自用路径没有超过三层所以没发现，已经修复了。
@mzszhznn

**Comment by mzszhznn** [comment]
@helloqiu 我刚下载了最新前端目录，编译输出的结果替换老的。
重新启动服务，我遇到的问题还在的。
config
│  $items.xls
│
├─前端模块配置
│      autoOpenPanel.xls
│      backgroundDef.xls
│      closeBetaAd.xls

        查看的目录是config目录，“$items.xls” 文件和 ”前端模块配置” 文件夹能查看到，点击“前端模块配置”后，里面的内容为空。

**Comment by helloqiu** [comment]
我似乎并不能重现，建议用 npm 或者 docker，或者检查一下 ```/api/scan``` 的输出，或者试试 develop 分支。
@mzszhznn 
![image](https://cloud.githubusercontent.com/assets/8971659/22920991/cfe69cea-f2d2-11e6-9193-213604f5e9f3.png)
![image](https://cloud.githubusercontent.com/assets/8971659/22921007/dff78ea0-f2d2-11e6-8879-e410d197043b.png)
![image](https://cloud.githubusercontent.com/assets/8971659/22921178/84af6684-f2d3-11e6-9ab3-3cf39ff75d95.png)

**Comment by mzszhznn** [comment]
/api/scan 这个结果是正常的，那我先试试分支的

**Comment by mzszhznn** [comment]
var tree = dirtree('./test/');

var options = {
  'recursive': true
};

fs.watch('./test/', options, function () {
  tree = dirtree('./test/');
});
找到原因了，是因为我修改了dirtree查找的目录导致的。我是在我得模块中使用到了online-explorer，想动态的指向路径.导致浏览器地址栏在点击文件夹时前面会多了一个目录。
![image](https://cloud.githubusercontent.com/assets/11714000/22925161/a87af1c8-f2e2-11e6-9ba7-3a20c5f7797b.png)

如果支持require 选项可以传递目录就更好了 

@helloqiu 非常感谢您的答复。

**Comment by helloqiu** [comment]
现在应该可以了
@mzszhznn

**Comment by mzszhznn** [comment]
非常感谢
